name: recommenderdemo
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - joblib=1.3.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.25
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - ncurses=6.4
  - numpy=1.26.2
  - openssl=3.2.0
  - pandas=2.1.4
  - pip=23.3.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - readline=8.2
  - scikit-surprise=1.1.3
  - scipy=1.11.4
  - setuptools=68.2.2
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - aiosqlite==0.19.0
      - attrs==23.1.0
      - discord-py==2.3.2
      - frozenlist==1.4.0
      - fuzzywuzzy==0.18.0
      - idna==3.6
      - levenshtein==0.23.0
      - multidict==6.0.4
      - python-dotenv==1.0.0
      - python-levenshtein==0.23.0
      - rapidfuzz==3.5.2
      - scikit-learn==1.3.2
      - threadpoolctl==3.2.0
      - yarl==1.9.4
